app/main/forms.py
from flask import flash
from flask_wtf import Form
from ..models import Facility, Maintainer, RepairRequests, RepairStatus
from wtforms import SubmitField, SelectField, StringField, TextAreaField, IntegerField, BooleanField, HiddenField
from wtforms.validators import Required, Length, ValidationError, Regexp, Email, NumberRange


class AddFacilityDetailsForm(Form):
    facility_name = StringField("Facility Name",validators=[Required(), Length(8, 50)])
    facility_description = TextAreaField("Detailed Information")
    
    submit = SubmitField("Submit")
    #validate facility name
    def validate_name(self, field):
        if Facility.query.filter_by(facility_name=field.data).first():
            raise ValidationError("This Facility already exists.")

class AddMaintainerForm(Form):
    name = StringField("Name ", validators=[Required(), Length(8, 50)])
    phone_no  = IntegerField("phone_no", validators = [])
    submit = SubmitField("Add")


class RepairDetailsForm(Form):
    facility = SelectField("Facility", coerce=int)
    description = StringField("Description", validators=[Required(), Length(10, 255)])
    

    def __init__(self, *args, **kwargs):
        super(RepairDetailsForm, self).__init__(*args, **kwargs)
        self.facility.choices = [
            (i.id, i.facility_name) for i in Facility.query.order_by(Facility.facility_name).all()]


class RequestRepairForm(RepairDetailsForm):
    submit = SubmitField("Submit")

    def __init__(self, *args, **kwargs):
        super(RequestRepairForm, self).__init__(*args, **kwargs)

class RejectRepairForm(Form):
    reasons = TextAreaField("Comments.")

   
class AssignToForm(Form):
    name = SelectField("Name", coerce=int)
    message = TextAreaField("message")

    def __init__(self, *args, **kwargs):
        super(AssignToForm, self).__init__(*args, **kwargs)
        self.name.choices = [
            (i.id, i.name) for i in Maintainer.query.order_by(Maintainer.name).all()
        ]

   
    

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, url_for, redirect, abort, flash, request, current_app
from flask_login import login_required, current_user
from app import db
from app.main import main
from ..models import User, Facility, Maintainer, RepairRequests, RepairStatus, RepairAssignments

from app.main.forms import (
   AddFacilityDetailsForm, AddMaintainerForm, AssignToForm, RepairDetailsForm, RequestRepairForm, RejectRepairForm 
)

@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = AddFacilityDetailsForm()
    template = 'main/add_facility.html'
    if current_user.is_admin:
        if form.validate_on_submit():
            facility = Facility( 
                    facility_name= form.facility_name.data,
                    facility_description = form.facility_description.data
                    )
            db.session.add(facility)
            db.session.commit()
            flash('You have added a facility')
            return redirect(url_for('main.index'))
    else:
        template = 'main/request_repair.html'
        form = RequestRepairForm()
        if form.validate_on_submit():
            repair = RepairRequests(
                requested_by=current_user.id,
                facility_id=form.facility.data,
                description=form.description.data,
                
            )
            db.session.add(repair)
            db.session.commit()     
            flash('Request Received.')
            return redirect(url_for('main.index'))

    return render_template(template, form=form)
  
        
@main.route('/add_repair_persons', methods=['GET','POST'])
@login_required
def add_maintainer():
    form = AddMaintainerForm()
    if form.validate_on_submit():
        repairPerson = Maintainer( 
            name= form.name.data,
            phone_no = form.phone_no.data 
        )
        db.session.add(repairPerson)
        db.session.commit()
        flash('You have added a maintainer')
        return redirect(url_for('main.add_maintainer'))
    return render_template('main/add_maintainer.html', form=form)

       
@main.route('/view-repairs/<int:repair_id>')
@login_required
def view_repairs(repair_id):
    repair = RepairRequests.query.get_or_404(repair_id)
    if not (current_user.is_admin):
        if RepairRequests.requested_by != current_user.id:
            abort(403)
    return render_template('main/repair_detail.html', repair=repair)


@main.route('/new-requests', methods=['GET', 'POST'])
@login_required
def view_new_requests():
    if current_user.is_admin:
        repairs = RepairRequests.query.filter_by(progress=0, confirmed=False).order_by(RepairRequests.date_requested.desc()).all()
    
    return render_template('main/new_requests.html', repairs=repairs)


@main.route('/repairs/reject/<int:repairs_id>', methods=['GET', 'POST'])
@login_required
def reject_repair_request(repairs_id):
    if not current_user.is_admin:
        abort(403)
    repair = RepairRequests.query.get_or_404(repairs_id)
    form = RejectRepairForm()

    if request.method == 'GET':
        temp = {
            'description': repair.description,
            'date_requested': repair.date_requested,
            'facility': repair.facility,
            'reasons': form.reasons.data
        }
        db.session.delete(repair)
        db.session.commit()
        return redirect(url_for('main.view_new_requests'))
    return render_template('main/new_requests.html', repair=repair, form=form)


@main.route('/request-progress')
@login_required
def view_request_progress():
    if current_user.is_admin:
        repairs = RepairAssignments.query.all()

    return render_template('main/request_progress.html', repairs=repairs)  

@main.route('/assign', methods=['GET', 'POST'])
@login_required
def assign_maintainer():
    repairs_id = request.args.get('id')
    form = AssignToForm()
    if form.validate_on_submit():
        assign = RepairAssignments(
            maintainer_id = form.name.data,
            message =form.message.data,
            repair_id = repairs_id
            )
        db.session.add(assign)
        db.session.commit()

        repair = RepairRequests.query.filter_by(id=repairs_id).first()
        repair.progress = 1
        db.session.commit()

        return redirect(url_for('main.view_new_requests'))

    return render_template('main/assign_repair.html', form=form)


@main.route('/notifications', methods=['GET', 'POST'])
@login_required
def view_notifications():
    repair_requests = RepairRequests.query.filter(RepairRequests.requested_by == current_user.id).all()
    results = []
    for req in repair_requests:
        results.append(req.id)

    repairs = RepairAssignments.query.filter(RepairAssignments.id.in_(results)).all()
    return render_template('main/notifications.html', repairs=repairs) 

app/templates/main/add_facility.html
{% extends "main/index.html" %}

{% block dashboard %}
    <div class="row">
        <h1 class="text-center">Add Facility</h1>
        
        <div class="col-sm-10 col-sm-offset-1">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock dashboard %}

app/templates/main/add_maintainer.html
{% extends "main/index.html" %}

{% block dashboard %}
    <div>
        <h1 class="text-center">Add Repair Persons</h1>
        
        <div class="col-sm-10 col-sm-offset-1">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock dashboard %}

app/templates/main/assign_repair.html
{% extends "main/index.html" %}

{% block dashboard %}

    <div class="row heading">
        <div class="col-md-4">Requested by</div>
        <div class="col-md-4">Description</div>
        <div class="col-md-4">Actions</div>
    </div>
    <br/>

    <div class="row">
    <div class="panel panel-default">
        <div class="panel-body">
            <form  method="post">
                {{ form.hidden_tag() }}
                {{ wtf.form_errors(form, hiddens="only") }}
                
                {{ wtf.form_field(form.name) }}
                {{ wtf.form_field(form.message) }}
                <button type="submit" class="btn btn-default">Save</button>
            </form>
        </div>
    </div>
    </div>

{% endblock dashboard %}

app/templates/main/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}MainTrackor - Home Page{% endblock %}

{% block content %}
    
    <div class="row">
        <div class="container dashboard">
            <div class="col-sm-3" >
                <div class="row">
                    <div class="list-group">
                        {% if current_user.is_admin %}
                        <a href="{{ url_for('main.index') }}" class="list-group-item selected">Add Facility</a>
                        <a href="{{ url_for('main.add_maintainer') }}" class="list-group-item">Add a Maintener</a>
                        <a href="{{ url_for('main.view_new_requests') }}" class="list-group-item">View New Requests</a>
                        <a href="{{ url_for('main.view_request_progress') }}" class="list-group-item">View Progress</a>
                        {% else %}
                        <a href="{{ url_for('main.index') }}" class="list-group-item">Make Request</a>
                        <a href="{{ url_for('main.view_notifications') }}" class="list-group-item">Notifications
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-sm-9">
                <div class="row">
                    {% for message in get_flashed_messages() %}
                        <div class="alert alert-warning" alert-dismissible" role="alert>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                            {{ message }}                    
                        </div>
                    {% endfor %}
                    
                    
                    <div class="col-sm-11 col-sm-offset-1">
                        {% block dashboard %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/main/new_requests.html
{% extends "main/index.html" %}

{% block dashboard %}

    <div class="row heading">
        <div class="col-md-4">Requested by</div>
        <div class="col-md-5">Description</div>
        <div class="col-md-3">Actions</div>
    </div>
    <br/>

    {% for repair in repairs %}
    <div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">{{repair.repair_req.username}}</div>
            <div class="col-md-5">{{repair.description}}</div>
            <div class="col-md-3">
            <a  class="btn btn-primary btn-sm" href="{{ url_for('main.assign_maintainer', id=repair.id) }}">Assign</a>
            {% set id_for_repair = repair.id %}
            <a href="{{ url_for('main.reject_repair_request', repairs_id=repair.id)}}" class="btn btn-danger btn-sm">Reject</a>
            </div>
        </div>
    </div>
    </div>
    {% endfor %}

{% endblock dashboard %}

app/templates/main/notifications.html
{% extends "main/index.html" %}

{% block dashboard %}

    <div class="row heading">
      
        <div class="col-md-3">Assigned To</div>
        <div class="col-md-3">Status</div>
    </div>
    <br/>
    
    {% for repair in repairs %}
         
        <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                
                <div class="col-md-3">{{repair.assignments.name}}</div>
                <div class="col-md-3">{{repair.repairs.status}}</div>
            </div>
        </div>
        </div>
    {%endfor%}

    
{% endblock dashboard %}

app/templates/main/repair_detail.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}
    MainTracker - Task Request
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            {% if current_user.is_admin or current_user.is_maintenance %}
                <a href="{{ url_for('main.index') }}"></a>
            </div>
        {% endif %}
    </div> <!-- row -->
{% endblock content %}

app/templates/main/repair_update.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    MainTracker - View Task
{% endblock title %}

{% block content %}
<div class="row update-page">
    <h1 class="page-header">Update repair: <a href="{{ url_for('main.view_repair', repair_id=repair.id)}}">{{ repair.description | truncate(40, True) | lower }}</a></h1>

    <div class="col-md-6">
        <h2>Repair Details</h2> <hr>
        {{ repair_det_panel.details_panel(repair) }}
    </div>
    <div class="col-md-6">
        <h2>Repair Update</h2> <hr>
        {{ macros.render_alert('alert-danger') }}
        {{ wtf.quick_form(form) }}
        {% if current_user.is_admin and not task.resolved %}
            <br>
            <a href="{{ url_for('main.reject_repair', repair_id=repair.id)}}" class="btn btn-danger">Reject Repair Request.</a>
        {% endif %}

    </div>
</div>
{% endblock content %}

app/templates/main/request_progress.html
{% extends "main/index.html" %}

{% block dashboard %}

    <div class="row heading">
        <div class="col-md-3">Requested by</div>
        <div class="col-md-3">Assigned To</div>
        <div class="col-md-3">Status</div>
        <div class="col-md-3">Actions</div>
    </div>
    <br/>
    
    {% for repair in repairs %}
        <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3">{{repair.repairs.repair_req.username}}</div>
                <div class="col-md-3">{{repair.assignments.name}}</div>
                <div class="col-md-3">{{repair.repairs.progress}}</div>
                <div class="col-md-3">
                    <button type="button" class="btn btn-success btn-sm">edit</button>
                </div>
            </div>
        </div>
        </div>
    {%endfor%}

    
{% endblock dashboard %}

app/templates/main/request_repair.html
{% extends "main/index.html" %}

{% block dashboard %}
    <div class="row">
        <h1 class="text-center">Make Maintenance Request.</h1>
        <div class="col-sm-8 col-sm-offset-2">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock dashboard %}